// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjw1MzBwJsUdOGpLQeUDhUwHOyrCY61BE',
    appId: '1:414609473719:web:e12041a79bed5ab66e4d32',
    messagingSenderId: '414609473719',
    projectId: 'official-chatbox-application',
    authDomain: 'official-chatbox-application.firebaseapp.com',
    storageBucket: 'official-chatbox-application.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXUYyQW_q_meUJlB0xl31Cf7kJRdDeO1Q',
    appId: '1:414609473719:android:c66f5838cbb4c2d06e4d32',
    messagingSenderId: '414609473719',
    projectId: 'official-chatbox-application',
    storageBucket: 'official-chatbox-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI_CgIuaEmxzlm41n_YBFpXzZo2I6948g',
    appId: '1:414609473719:ios:f61f644a0b1716a96e4d32',
    messagingSenderId: '414609473719',
    projectId: 'official-chatbox-application',
    storageBucket: 'official-chatbox-application.appspot.com',
    iosBundleId: 'com.example.chatbox',
  );
}
